/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication;
import java.sql.*;
import java.io.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Pradnya
 */
public class fTampilNilai extends javax.swing.JFrame {
    Koneksi kon = new Koneksi();
    
    public fTampilNilai() {
        initComponents();
        TampilData();
    }
    
    void TampilData (){
      DefaultTableModel TableData = new DefaultTableModel();
        TableData.addColumn("ID Nilai");
        TableData.addColumn("NIM");
        TableData.addColumn("Kelas");
        TableData.addColumn("Asisten");
        TableData.addColumn("Dosen");
        TableData.addColumn("Lp 1");
        TableData.addColumn("Lp 2");
        TableData.addColumn("Lp 3");
        TableData.addColumn("Lp 4");
        TableData.addColumn("Lp 5");
        TableData.addColumn("Lp 6");
        TableData.addColumn("Lp 7");
        TableData.addColumn("Lp 8");
        TableData.addColumn("Lp 9");
        TableData.addColumn("Lp 10");
        TableData.addColumn("Lp 11");
        TableData.addColumn("Lp 12");
        TableData.addColumn("Lp 13");
        TableData.addColumn("Lp 14");
        
        try {
            kon.konek();
            String sql = "select * from tbl_nilai";
            kon.st = kon.conn.createStatement();
            kon.rs = kon.st.executeQuery(sql); //menjalankan query
            while (kon.rs.next()) {
                TableData.addRow(new Object[]{kon.rs.getString(1),kon.rs.getString(2),
                kon.rs.getString(3),kon.rs.getString(4),kon.rs.getString(5),kon.rs.getString(6),
                kon.rs.getString(7),kon.rs.getString(8),kon.rs.getString(9),kon.rs.getString(10),
                kon.rs.getString(11),kon.rs.getString(12),kon.rs.getString(13),kon.rs.getString(14),
                kon.rs.getString(15),kon.rs.getString(16),kon.rs.getString(17),kon.rs.getString(18),
                kon.rs.getString(19)});
            }
           jTblNilai.setModel(TableData);
        } catch (Exception e) {
            
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblNilai = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BtnInputNilai = new javax.swing.JButton();
        jBtnUpdateNilai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jTblNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Nilai", "NIM", "Kelas", "Asisten", "Dosen", "Lp 1", "Lp 2", "Lp 3", "Lp 4", "Lp 5", "Lp 6", "Lp 7", "Lp 8", "Lp 9", "Lp 10", "Lp 11", "Lp 12", "Lp 13", "Lp 14"
            }
        ));
        jScrollPane1.setViewportView(jTblNilai);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATA NILAI PRAKTIKUM");

        jButton1.setText("Tutup");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BtnInputNilai.setText("INPUT NILAI");
        BtnInputNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInputNilaiActionPerformed(evt);
            }
        });

        jBtnUpdateNilai.setText("UPDATE NILAI");
        jBtnUpdateNilai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnUpdateNilaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(BtnInputNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnUpdateNilai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(BtnInputNilai)
                    .addComponent(jBtnUpdateNilai))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnInputNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInputNilaiActionPerformed
        fTambahNilai tn = new fTambahNilai();
        tn.setVisible(true);
    }//GEN-LAST:event_BtnInputNilaiActionPerformed

    private void jBtnUpdateNilaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnUpdateNilaiActionPerformed
        // TODO add your handling code here:
        fUpdateNilai un = new fUpdateNilai();
        un.setVisible(true);
    }//GEN-LAST:event_jBtnUpdateNilaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fTampilNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fTampilNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fTampilNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fTampilNilai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fTampilNilai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnInputNilai;
    private javax.swing.JButton jBtnUpdateNilai;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblNilai;
    // End of variables declaration//GEN-END:variables
}
